import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createIdempotencyStore } from '../tools/basecamp-adapters/src/idempotency.mjs';
import { createBugBoardAdapter, createUpdateBoardAdapter, linkCards } from '../tools/basecamp-adapters/src/adapters.mjs';
import { BOARDS } from '../tools/basecamp-adapters/src/contracts.mjs';
const bug = { card_id:'BUG-1', client:'Fictional Harbor Co', project:'Margin Helper', original_message:'The answer is wrong.', owner:'Lilly', next_action:'Check saved copy.', evidence_links:'https://example.test/report', final_client_email_link:'https://example.test/email', stage:'New' };
const update = { card_id:'UPDATE-1', client:'Fictional Harbor Co', project_id:'PROJECT-FAKE-001', linked_bug_card_id:'BUG-1', change_summary:'Correct rule.', lilly_approver:'Lilly', release_record_link:'https://example.test/release', post_update_check:'Run the Test Library.', rollback_action:'Restore the approved copy.', stage:'Proposed' };
async function adapters() { const dir = await mkdtemp(path.join(os.tmpdir(), 'ww-basecamp-')); const store = createIdempotencyStore(path.join(dir, 'claims.json')); return { dir, bugs: createBugBoardAdapter({ store }), updates: createUpdateBoardAdapter({ store }) }; }
test('routes bug and update cards to separate idempotent actions', async () => { const a = await adapters(); try { const firstBug = await a.bugs.receive(bug, { boardUrl: BOARDS.bugs.url }); const secondBug = await a.bugs.receive(bug, { boardUrl: BOARDS.bugs.url }); const firstUpdate = await a.updates.receive(update, { boardUrl: BOARDS.updates.url }); const secondUpdate = await a.updates.receive(update, { boardUrl: BOARDS.updates.url }); assert.equal(firstBug.status, 'started'); assert.equal(secondBug.status, 'duplicate'); assert.equal(firstUpdate.status, 'queued'); assert.equal(secondUpdate.status, 'duplicate'); assert.deepEqual(linkCards(bug, update), { bug_card_id:'BUG-1', update_card_id:'UPDATE-1' }); } finally { await rm(a.dir, { recursive:true, force:true }); } });
test('rejects malformed cards and unknown boards with clear failures', async () => { const a = await adapters(); try { await assert.rejects(() => a.bugs.receive({ ...bug, owner:'' }, { boardUrl: BOARDS.bugs.url }), /Malformed card/); await assert.rejects(() => a.bugs.receive(bug, { boardUrl: BOARDS.updates.url }), /Unknown board context/); await assert.rejects(() => a.bugs.receive(bug, { boardUrl: BOARDS.bugs.url, knownCardIds: ['BUG-OTHER'] }), /Unknown card context/); await assert.rejects(() => a.updates.receive({ ...update, stage:'New' }, { boardUrl: BOARDS.updates.url }), /Invalid update stage/); } finally { await rm(a.dir, { recursive:true, force:true }); } });

test('simultaneous claims allow only one owner', async () => { const a = await adapters(); try { const claims = await Promise.all(Array.from({ length: 20 }, (_, index) => a.bugs.receive({ ...bug, card_id: 'BUG-CONCURRENT' }, { boardUrl: BOARDS.bugs.url }))); assert.equal(claims.filter((claim) => claim.status === 'started').length, 1); assert.equal(claims.filter((claim) => claim.status === 'duplicate').length, 19); } finally { await rm(a.dir, { recursive:true, force:true }); } });
test('deployed, verified, and blocked updates do not queue release actions', async () => { const a = await adapters(); try { for (const stage of ['Deployed', 'Verified', 'Blocked']) await assert.rejects(() => a.updates.receive({ ...update, card_id: `UPDATE-${stage}`, stage }, { boardUrl: BOARDS.updates.url }), /cannot start a release action/); } finally { await rm(a.dir, { recursive:true, force:true }); } });
