import assert from 'node:assert/strict';
import { mkdtemp, readdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { spawnSync } from 'node:child_process';
import { runClientProjectCheck } from '../tools/check-client-project/src/checker.mjs';
const rootDir = path.resolve(new URL('..', import.meta.url).pathname);
const fixture = (name) => path.join(rootDir, 'fixtures/basecamp', name);
const base = { clientName: 'Fictional Harbor Co', project: { id: 'PROJECT-FAKE-001', name: 'Fictional Margin Helper', savedCopyLocation: 'fixture' }, testLibraryPath: fixture('test-library.json'), mode: 'fake' };
test('passing saved copy writes one healthy Health Report', async () => { const out = await mkdtemp(path.join(os.tmpdir(), 'ww-check-')); try { const result = await runClientProjectCheck({ ...base, controlCenterDir: out, savedCopyPath: fixture('saved-copy-pass.json') }); assert.equal(result.status, 'healthy'); assert.equal(result.failed.length, 0); assert.equal((await readdir(path.join(out, 'reports'))).length, 1); assert.deepEqual(await readdir(path.join(out, 'issues')), []); } finally { await rm(out, { recursive: true, force: true }); } });
test('failed saved copy automatically starts exactly one deep check', async () => { const out = await mkdtemp(path.join(os.tmpdir(), 'ww-check-')); try { const input = { ...base, controlCenterDir: out, savedCopyPath: fixture('saved-copy-fail.json') }; const first = await runClientProjectCheck(input); const second = await runClientProjectCheck(input); assert.equal(first.status, 'needs review'); assert.ok(first.deepCheck); assert.equal(first.deepCheck.plan.rootCause.category, 'project rule'); assert.equal(second.deepCheck.result.created.length, 0); assert.equal((await readdir(path.join(out, 'issues'))).filter((name) => name.includes('DEEP-PROJECT-FAKE-001')).length, 2); } finally { await rm(out, { recursive: true, force: true }); } });

test('Test Library rejects missing refresh date and scope', async () => { const out = await mkdtemp(path.join(os.tmpdir(), 'ww-library-')); try { const original = JSON.parse(await (await import('node:fs/promises')).readFile(fixture('test-library.json'), 'utf8')); for (const field of ['refresh_date', 'scope']) { const broken = JSON.parse(JSON.stringify(original)); delete broken.tests[0][field]; const file = path.join(out, `${field}.json`); await writeFile(file, JSON.stringify(broken)); await assert.rejects(() => import('../tools/check-client-project/src/checker.mjs').then(({ loadTestLibrary }) => loadTestLibrary(file)), new RegExp(`missing ${field}`)); } } finally { await rm(out, { recursive: true, force: true }); } });

test('CLI passes repository root to output safety guard', () => { const cli = path.join(rootDir, 'tools/check-client-project/src/cli.mjs'); const result = spawnSync(process.execPath, [cli, '--mode', 'fake', '--control-center', rootDir, '--saved-copy', fixture('saved-copy-pass.json'), '--test-library', fixture('test-library.json'), '--client', 'Fictional Harbor Co', '--project-id', 'PROJECT-FAKE-001', '--project-name', 'Fictional Margin Helper'], { encoding: 'utf8' }); assert.notEqual(result.status, 0); assert.match(`${result.stderr}${result.stdout}`, /Output path must be outside the repository/); });
