export const BOARDS = Object.freeze({
  bugs: { key: 'bugs', name: 'Client Debug Tickets', url: 'https://app.basecamp.com/5730006/buckets/48267142/card_tables/10133060890', stages: ['New', 'In progress', 'Complete', 'Client verified complete'], fields: ['client', 'project', 'original_message', 'owner', 'next_action', 'evidence_links', 'final_client_email_link'] },
  updates: { key: 'updates', name: 'Client Updates', url: 'https://app.basecamp.com/5730006/buckets/48267142/card_tables/10197329775', stages: ['Proposed', 'Approved', 'Deployed', 'Verified', 'Blocked'], fields: ['client', 'project_id', 'linked_bug_card_id', 'change_summary', 'lilly_approver', 'release_record_link', 'post_update_check', 'rollback_action'] },
});
export const BUG_STAGES = BOARDS.bugs.stages;
export const UPDATE_STAGES = BOARDS.updates.stages;
const nonempty = (name, value) => { if (typeof value !== 'string' || !value.trim()) throw new Error(`Malformed card: ${name} is required.`); };
export function validateBoardContext(context, kind) { const board = BOARDS[kind]; if (!board || context?.boardUrl !== board.url) throw new Error(`Unknown board context for ${kind}.`); return board; }
export function validateBugCard(card, context) { validateBoardContext(context, 'bugs'); if (Array.isArray(context?.knownCardIds) && !context.knownCardIds.includes(card?.card_id)) throw new Error(`Unknown card context: ${card?.card_id || '(missing)'}.`); for (const field of BOARDS.bugs.fields) nonempty(field, card[field]); if (!BUG_STAGES.includes(card.stage)) throw new Error(`Invalid bug stage: ${card.stage}.`); nonempty('card_id', card.card_id); return card; }
export function validateUpdateCard(card, context) { validateBoardContext(context, 'updates'); if (Array.isArray(context?.knownCardIds) && !context.knownCardIds.includes(card?.card_id)) throw new Error(`Unknown card context: ${card?.card_id || '(missing)'}.`); for (const field of BOARDS.updates.fields.filter((field) => field !== 'linked_bug_card_id')) nonempty(field, card[field]); if (!UPDATE_STAGES.includes(card.stage)) throw new Error(`Invalid update stage: ${card.stage}.`); nonempty('card_id', card.card_id); if (card.linked_bug_card_id && typeof card.linked_bug_card_id !== 'string') throw new Error('Malformed card: linked_bug_card_id must be text.'); return card; }
